[module.hugoVersion]
extended = true
min = "0.56.0"

[[module.imports]]
path = "github.com/dnb-hugo/libraries/bootstrap5"
disabled = false

[[module.imports]]
path = "github.com/dnb-hugo/components/functions"
disabled = false

[[module.imports]]
path = "github.com/dnb-hugo/debugprint"
disabled = false
